import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "../../components/Sidebar"; // Adjust path as needed
import "./dashboard/globals.css";
import React from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "My Dashboard App",
    description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    // Render a container div instead of <html>/<body> so this group layout nests correctly
    // under the root layout which is responsible for the actual <html> and <body> tags.
    return (
        <div
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            style={{
                display: "flex",
                height: "100vh",
                fontFamily: "'Inter','DM Sans','Segoe UI',sans-serif",
                background: "#13141f",
                overflow: "hidden", // Prevent double scrollbars
                margin: 0,
            }}
        >
            {/* Persistent Sidebar */}
            <Sidebar />

            {/* Page Content Area */}
            <main
                style={{
                    flex: 1,
                    overflowY: "auto",
                    background: "#13141f",
                    display: "flex",
                    flexDirection: "column",
                }}
            >
                {children}
            </main>
        </div>
    );
}
