import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "../components/Sidebar"; // Adjust path as needed
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "My Dashboard App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            {/* 1. Global background and flex-row setup */}
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                style={{
                    display: "flex",
                    height: "100vh",
                    fontFamily: "'Inter','DM Sans','Segoe UI',sans-serif",
                    background: "#13141f",
                    overflow: "hidden", // Prevent double scrollbars
                    margin: 0,
                }}
            >
                {/* 2. Persistent Sidebar */}
                <Sidebar />

                {/* 3. Page Content Area */}
                <main
                    style={{
                        flex: 1,
                        overflowY: "auto",
                        background: "#13141f",
                        display: "flex",
                        flexDirection: "column",
                    }}
                >
                    {children}
                </main>
            </body>
        </html>
    );
}
